### ISSUE TITLE
Configuration issue with ingestsip.py

### ISSUE THREAD

**Issue by kieranjol** [BAM-PFA/pymm#13]
I'm using Ubuntu 16.04 and I have not filled in any entries in the config file.

I wanted to try out ingestsip and see how far I could get without setting the config file.

I received some configuration errors (from here: https://github.com/BAM-PFA/pymm/blob/master/pymmFunctions.py#L48) which led me to believe that I could set certain key paths via CLI arguments,but that does not seem to be the case:

```
~/pymm$ ./ingestSip.py --resourcespace_deliver '/home/kieran/Downloads/Untitled Folder' --aip_staging '/home/kieran/Downloads/Untitled Folder'  --outdir_ingestfile '/home/kieran/Downloads/Untitled Folder' 

				CONFIGURATION PROBLEM:
				You have not yet set a valid directory for 'aip_staging.' Please run pymmConfig.py,
				edit the config file directly,
				or use '--aip_staging' to set the AIP storage path.
				HINT: Check that the filepath is entered correctly.
				

				CONFIGURATION PROBLEM:
				You have not yet set a valid directory for 'resourcespace_deliver.' Please run pymmConfig.py,
				edit the config file directly,
				or use '--resourcespace_deliver' to set the resourcespace output path.
				HINT: Check that the filepath is entered correctly.
				

				CONFIGURATION PROBLEM:
				You have not yet set a valid directory for 'outdir_ingestfile.' Please run pymmConfig.py,
				edit the config file directly,
				or use '--outdir_ingestfile' to set the ingestfile output path.
				HINT: Check that the filepath is entered correctly.
				

You are missing some required file paths and we have to quit. Sorry.
```

**Comment by kieranjol** [comment]
```
$ cat pymmconfig/config.ini 
[paths]
outdir_ingestfile:
aip_staging:
resourcespace_deliver:
prores_deliver:				

[deriv delivery options]
resourcespace: n
proresHQ: n				

[database settings]
use_db:
pymm_db:
pymm_db_access:
pymm_db_address:				

[database users]
user: password				

[logging]
pymm_log_dir:				

[mediaconch format policies]
film_scan_master:
video_capture_master:
magnetic_video_mezzanine:
film_scan_mezzanine:
low_res_proxy:				

[ffmpeg]
resourcespace_opts:["a","b","c"]
proresHQ_opts:["x","y","z"]

```

**Comment by mcampos-quinn** [comment]
Hey thanks for checking it out! Yeah, I think I was going to add CLI options for those paths but never actually did, then forgot to remove those error messages. 

I might just remove the error messages, but it would be simple enough to add the CLI functionality... I'll see what I have time for this week. 

Thanks so much for giving it a whirl and letting me know about this!

**Comment by kieranjol** [comment]
Either options sound good to me,might be easier to maintain to just stick with config alone and remove the cli options. 

The only benefit I see to have  the CLI options  is that the scripts will be easier to pick up and play if you have the CLI options.I've rarely ever used many mediamicroservices scripts,mostly cos I don't wanna fill out the config due to laziness. Just snooping at the source code has been my main engagement.

**Comment by mcampos-quinn** [comment]
I *think* this should be usable without config settings by declaring CLI options:
`-a` for aip staging
`-o` for output dir
`-r` for resourcespace (our 'access copy') delivery

Unfortunately I don't have a ton of time to test it out super thoroughly now  :( 
It definitely is easier to just maintain config settings and there's  a chance this will lose out to updates down the road. For the moment if you run it with a blank `config.ini` I have it write a system log to the desktop and it transcodes a proxy file with some default settings.

A later goal will definitely be to get a `test` mode up and running where it does either a dry run without transcoding anything, or just outputs everything to a temp folder on the Desktop or something. 

Thanks again for taking the time to look at it and contribute!

**Comment by kieranjol** [comment]
Brilliant!I I look forward to trying it out,and I will end up using the config.
