### ISSUE TITLE
ingestSip - processingVars unset variable

### ISSUE THREAD

**Issue by kieranjol** [BAM-PFA/pymm#16]
Hey, so on my very first run, I triggered an error but ingestSip exited due to what appears to be an unset variable. The error disappeared when I ran the script again and I used the `--operator` flag. Perhaps some key files or log locations were then made available to the script on the second run?:

```
$ python3 ingestSip.py -i /Volumes/hi2u/kieran_tests/AF5841\ Irish\ Holiday\ IFA-2013-34.mov 
input is a single file

					CONFIGURATION PROBLEM:
					YOU FORGOT TO SET operator. It is required.
					Try again, but set operator with the flag --operator
Traceback (most recent call last):
  File "ingestSip.py", line 1503, in <module>
    main()
  File "ingestSip.py", line 1022, in main
    processingVars,
UnboundLocalError: local variable 'processingVars' referenced before assignment

```

**Comment by mcampos-quinn** [comment]
bah! I think it was just the missing `operator` flag. I'll make it a required argument.
