### ISSUE TITLE
Can I fork pymmconfig?

### ISSUE THREAD

**Issue by kieranjol** [BAM-PFA/pymm#25]
I know the license covers this, but I want to implement a config file soon and by the looks of your code, it looks like you've caught a lot of issues in advance so I might just copy-pasta the whole thing and tweak it as needs be. Just thought I'd give you a heads up!

**Comment by mcampos-quinn** [comment]
Yes by all means! The script to compile the config.ini on the CLI contains some wonky interview questions that I should have made clearer/less implicit. FYI. I'll keep an eye out to see how it goes!

**Comment by kieranjol** [comment]
Hey, weird request - would you be able to open a PR in ifiscripts with just a copy paste of pymmconfig? This way you're credited in the commit history rather than me being the author from the first commit. I can always do the copypaste myself and give you credit in the docs/comments but i think the PR way is better..

**Comment by kieranjol** [comment]
p.s - just thepymmconfig script in the root of the repo..

**Comment by mcampos-quinn** [comment]
Sure! I won't get to it before tomorrow ;) I'm so glad it might be useful
to you!

**Comment by kieranjol** [comment]
Merci!
