### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by kieranjol** [BAM-PFA/pymm#26]
I just realised while making #25 that there is no license for this project.

**Comment by mcampos-quinn** [comment]
:'( I know. I think I have been intimidated by the options and put off choosing a license. I'll look at it for real this week. Thanks for the reminder!

**Comment by kieranjol** [comment]
I never thought about it that much and just picked MIT. I've been
considering changing it but I probably won't..

**Comment by mcampos-quinn** [comment]
UC Berkeley also has some anal retentive rules about intellectual property created by employees for their work. I think I saw that and put my head in the sand but luckily there are lots of people here I can ask for advice :)

**Comment by kieranjol** [comment]
ahhhhh, i flew under the radar with that one. best of luck!

**Comment by mcampos-quinn** [comment]
finally read the UC policy, it's no big deal for something like this (they are just keeping an eye out for $$ makers)
