### ISSUE TITLE
test viability of hashdeep_audit() on LTO

### ISSUE THREAD

**Issue by mcampos-quinn** [BAM-PFA/pymm#5]
Need to make sure that `makeMetadata.hashdeep_audit()` is able to use `os.chdir` and stuff to verify a package once it's been written to LTO. And stuff.

**Comment by kieranjol** [comment]
I'm curious to know how that goes for you - I think I was having
multithreaded issues - md5deep would try to hash like 4 files at a time, so
it would just start spinning up and down forever and wouldn't really do
anything. I don't think specifying singlethreading helped too much either
as I think hashdeep might have been reading the files not in alphabetical
order, which is usually fine on a spinning disk but not on a tape (assuming
the files were wrtitten in alphabetical order). Though a lot of these
issues are made a lot worse with image sequences, though they can be a pain
with large files too.

**Comment by mcampos-quinn** [comment]
I'm not going to hold my breath... but man it would be convenient if it just worked!

Thanks for sharing those roadblocks you found. I will have a better sense of where to start troubleshooting. Definitely will let you know what I find out, probably late this week.

**Comment by kieranjol** [comment]
Cool, validating checksums on tape can work great - I think Dave doesn't do it, he pulls the files off, then validates those..

**Comment by mcampos-quinn** [comment]
In the fragile testing environment I set up this is looking good with some caveats: 
* need to rethink the supplied paths... something is funny in the creation of audit files when reading objects on tape. Possibly trying to write the audit file to tape while doing the hash checks makes it hang...¿?
* also supplying the manifest as '../manifestpath.txt' rather than the full path to the mounted tape seems to prevent hanging

Definitely experienced the spin/wait/hang/spin loop mentioned above. Also testing hashdeep directly helped to suss out these potential solutions.

**Comment by mcampos-quinn** [comment]
Seems to be just fine. 
Removed the actual writing of the audit file altogether from initial test. Maybe will be added back in later?
