### ISSUE TITLE
idea: object-oriented ingest

### ISSUE THREAD

**Issue by mcampos-quinn** [BAM-PFA/pymm#7]
to do: 
explore ingest process as an object class with various attributes:
* object being ingested
* status
* other crap now in `processingVars` dictionary

this would simplify some of the flow of data through the process. and i think it would also make things like database reporting much simpler.
```
class Ingest(argDict):
    # input args as dict per the current processingVars dict?
    # or maybe
    def __init__(self,**kwargs):
        self.ingestObject = os.path.basename(inputPath)
       self.operator = operator
       ... etc ...
    def makeDerivs(self,inputObject):
        # do stuff
    def reportDB(self, self.inputObject):
        magicCnx = dbAccess.DB(user)
        do_query(magicCnx, superSQL)
```

fewd for thought.

**Comment by kieranjol** [comment]
Yeah, very interesting...

**Comment by kieranjol** [comment]
I was thinking about this again today, I think it's the way to go..

**Comment by mcampos-quinn** [comment]
Yes, I think it would have been better had I started with that approach. There are some elements of the ingest process that are fairly fragile that would have been better served with an object oriented approach (transcoding of derivatives, error handling, etc.).

I'm thinking of it as a next iteration, but there are a lot of steps between here and there for my work load.

**Comment by mcampos-quinn** [comment]
Closing as mostly done on ingest-refactor-compact
