### ISSUE TITLE
add system info to logs

### ISSUE THREAD

**Issue by mcampos-quinn** [BAM-PFA/pymm#9]
get it as a dict and... add it as a string to the start of the ingest logs?
import platform
info = platform.uname()
systemDict = dict(info._asdict())

**Comment by mcampos-quinn** [comment]
actually on mac this reports i386 processor which is incorrect.... :/ 
i'll look into it or find a different answer later.

**Comment by mcampos-quinn** [comment]
maybe seeing the incorrect processor architecture in `platform().processor` is not a big deal. `platform().machine` shows `x86_64` which is correct. also `uname -p` shows the same i386 value, which is similarly incorrect. so... 

there's a thread from 2010 where the python devs seem to shrug it off.
https://bugs.python.org/issue7860

closing for now, will implement this and ignore the processor value.

**Comment by mcampos-quinn** [comment]
Pleez steal!

I still don't really understand why the unix `uname` retrieves the wrong info.... but I'm not going to worry about it at least for now. The rest of the information shows that it's 64 bit architecture which is clear enough.

**Comment by kieranjol** [comment]
Me too,I tried looking at the `platform` python source code earlier and I
couldn't figure out how it ended up pulling that 32 bit value. .
